server:
  port: 8001

#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml
#  type-aliases-package: com.zy.micro.entity
#  mapper-locations:
#  - classpath:mybatis/mapper/**/*.xml

spring:
    application:
      name: microservices-dept
    datasourve:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/microservices
#      url: jdbc:oracle:thin:@10.252.95.133:1521:orcl
      password: 123
      username: root
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200

#      客户端注册到eureka服务列表内
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka    (单机)
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservices_8001      # 服务名称修改
    prefer-ip-address: true   # 访问路径显示IP地址


# info
info:
  app.name: ypl-microservices
  company.name: www.zy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$