server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.zy.micro.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
    application:
      name: microservices-dept
    datasourve:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:oracle:thin:@10.252.95.133:1521:hrdb
      password: rank2017_boehr
      username: rank
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200